version: '3.9'

services:
    app:
        container_name: character_ai_bot
        build: .
        ports:
            - '5080:5080'
        depends_on:
            - redis
            - database
        env_file:
            - config/.env
        volumes:
            - ./:/app
    database:
        container_name: character_ai_bot_database
        image: postgres
        environment:
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=postgres
            - POSTGRES_DB=character_ai_bot
        ports:
            - '5432:5432'
        volumes:
            - postgres-data:/var/lib/postgresql/data

    redis:
        container_name: character_ai_bot_redis
        image: redis
        ports:
            - '6379:6379'
        command: redis-server --requirepass redis
        volumes:
            - redis-data:/var/lib/redis/data

volumes:
    postgres-data:
    redis-data: